apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spinnaker-operator
  template:
    metadata:
      labels:
        name: spinnaker-operator
    spec:
      serviceAccountName: spinnaker-operator
      containers:
        - name: spinnaker-operator
          image: armory/spinnaker-operator:0.0.1
          command:
          - spinnaker-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "spinnaker-operator"
            - name: HALYARD_GENERATED
              value: "/var/halyard/generated"
          volumeMounts:
          - name: spinnaker-generated-volume
            mountPath: /var/halyard/generated
        - name: halyard
          image: armory/halyard-armory:poc
          volumeMounts:
          - name: halyard-config-volume
            mountPath: /opt/spinnaker/config
          - name: spinnaker-generated-volume
            mountPath: /var/halyard/generated
          ports:
          - containerPort: 8064
            protocol: TCP
      volumes:
      - name: halyard-config-volume
        configMap:
          name: my-halyard-config
      - name: spinnaker-generated-volume
        emptyDir: {}